modLoader="javafml" #mandatory
loaderVersion="[36,)" 
license="All rights reserved"
[[mods]] #mandatory
modId="chemie" #mandatory
version="1.0" #mandatory
displayName="Chemie Mod" #mandatory
logoFile="" #optional
credits="for Mr. Mint for his great textures" #optional
authors="Bretzelfresser and Mr. Mint" #optional
description='''
this Mod adds a lot of chemical Elements and their Reactions
'''
[[dependencies.chemie]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.chemie]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
